channels:
- conda-forge
dependencies:
- bzip2=1.0.8
- ca-certificates=2025.11.12
- libexpat=2.7.3
- libffi=3.5.2
- liblzma=5.8.1
- libsqlite=3.51.1
- libzlib=1.3.1
- openssl=3.6.0
- pip=25.3
- python=3.10.19
- setuptools=80.9.0
- tk=8.6.13
- tzdata=2025c
- ucrt=10.0.26100.0
- vc=14.3
- vc14_runtime=14.44.35208
- vcomp14=14.44.35208
- wheel=0.45.1
- pip:
  - anyio==4.12.0
  - attrs==25.4.0
  - beautifulsoup4==4.14.3
  - cached-property==2.0.1
  - certifi==2025.11.12
  - cffi==2.0.0
  - chardet==5.2.0
  - charset-normalizer==3.4.4
  - click==8.3.1
  - colorama==0.4.6
  - comtypes==1.4.14
  - cryptography==44.0.3
  - defusedxml==0.7.1
  - dnspython==2.8.0
  - docutils==0.22.3
  - et_xmlfile==2.0.0
  - exceptiongroup==1.3.1
  - exchangelib==5.6.0
  - fire==0.7.1
  - fonttools==4.61.1
  - fpdf2==2.8.5
  - furl==2.1.4
  - graphviz==0.21
  - h11==0.16.0
  - holidays==0.87
  - htmldocx==0.0.6
  - httpcore==1.0.9
  - httpx==0.28.1
  - idna==3.11
  - importlib_metadata==8.7.0
  - isodate==0.7.2
  - java-access-bridge-wrapper==2.0.0
  - jsonpath-ng==1.7.0
  - jsonschema==4.25.1
  - jsonschema-specifications==2025.9.1
  - lxml==6.0.2
  - more-itertools==10.8.0
  - mss==10.1.0
  - netsuitesdk==3.1.1
  - notifiers==1.3.6
  - O365==2.0.26
  - oauthlib==3.3.1
  - openpyxl==3.1.5
  - orderedmultidict==1.0.2
  - outcome==1.3.0.post0
  - packaging==25.0
  - pdfminer.six==20251107
  - pendulum==3.1.0
  - pillow==12.0.0
  - platformdirs==4.5.1
  - ply==3.11
  - psutil==7.1.3
  - pycparser==2.23
  - Pygments==2.19.2
  - PyJWT==2.10.1
  - pynput-robocorp-fork==5.0.0
  - pyotp==2.9.0
  - pypdf==6.4.2
  - pyperclip==1.11.0
  - PySocks==1.7.1
  - pyspnego==0.12.0
  - python-dateutil==2.9.0.post0
  - python-docx==1.2.0
  - python-dotenv==1.2.1
  - pytz==2025.2
  - pywin32==311
  - pywinauto==0.6.9
  - PyYAML==6.0.3
  - referencing==0.37.0
  - requests==2.32.5
  - requests-file==3.0.1
  - requests-oauthlib==2.0.0
  - requests-toolbelt==1.0.0
  - requests_ntlm==1.3.0
  - robocorp-storage==1.0.5
  - robotframework==7.4
  - robotframework-pythonlibcore==4.4.1
  - robotframework-requests==0.9.7
  - robotframework-sapguilibrary==1.1
  - robotframework-seleniumlibrary==6.8.0
  - robotframework-seleniumtestability==2.1.0
  - rpaframework==31.1.0
  - rpaframework-core==12.1.0
  - rpaframework-pdf==10.0.1
  - rpaframework-windows==10.0.3
  - rpds-py==0.30.0
  - selenium==4.15.2
  - simple-salesforce==1.12.9
  - six==1.17.0
  - smartsheet-python-sdk==3.0.2
  - sniffio==1.3.1
  - sortedcontainers==2.4.0
  - soupsieve==2.8
  - sspilib==0.5.0
  - stringcase==1.2.0
  - tenacity==8.5.0
  - termcolor==3.2.0
  - trio==0.32.0
  - trio-websocket==0.12.2
  - tweepy==4.16.0
  - typing_extensions==4.15.0
  - tzlocal==5.3.1
  - uiautomation==2.0.29
  - urllib3==2.6.2
  - validators==0.35.0
  - webdriver-manager==4.0.2
  - wrapt==1.17.3
  - wsproto==1.3.2
  - xlrd==2.0.2
  - xlutils==2.0.0
  - xlwt==1.3.0
  - zeep==4.3.2
  - zipp==3.23.0
